etl:
  url: https://www.openml.org/data/get_csv/16826755/phpMYEkMl
  na_value: '?'
  use_columns:
    - pclass
    - survived
    - name
    - sex
    - age
    - sibsp
    - parch
    - fare
    - embarked
  cols_categoric:
    - pclass
    - sex
    - embarked
  cols_numeric_float:
    - age
    - fare
  cols_numeric_int:
    - sibsp
    - parch
  cols_boolean:
    - survived

data:
  raw: data/01_raw/titanic_raw.csv
  intermediate: data/02_intermediate/titanic_type_fixed.parquet
