etl:
  url: https://www.openml.org/data/get_csv/16826755/phpMYEkMl
  use_columns:
    - pclass
    - survived
    - name
    - sex
    - age
    - sibsp
    - parch
    - ticket
    - fare
    - cabin
    - embarked
    - home.dest

data:
  raw: data/01_raw/titanic_raw.parquet
  processed: data/processed/processed.csv
  final: data/final/final.csv
